export const MENU_CATEGORIES = {
    GRILL_FEAST: "grill-feast",
    GRILL_PARADISE: "grill-paradise",
    EXTRAVAGANZA: "extravaganza",
    INTERNATIONAL: "international",
};

export const grillFeastItems = [
    {
        id: 1,
        name: "Caesar Salad",
        description: "Crisp romaine lettuce tossed with creamy Caesar dressing, Parmesan cheese, and homemade croutons.",
        image: "/images/menu/caesar-salad.png",
        price: 35,
    },
    {
        id: 2,
        name: "Grilled Chicken Bone",
        description: "Grilled chicken bone-in, seasoned to perfection and bursting with savory flavor, served with your choice of delectable sides.",
        image: "/images/menu/grilled-chicken.png",
        price: 65,
    },
    {
        id: 3,
        name: "Hummus",
        description: "Smooth and savory chickpea hummus, drizzled with extra virgin olive oil, and served with warm pita bread.",
        image: "/images/menu/hummus.png",
        price: 25,
    },
    {
        id: 4,
        name: "Pasta ( White or Pink )",
        description: "Al dente pasta served with your choice of creamy white sauce or tangy pink sauce, topped with freshly grated Parmesan cheese.",
        image: "/images/menu/pasta.png",
        price: 45,
    },
    {
        id: 5,
        name: "Tahina",
        description: "Rich and velvety tahini sauce made with sesame paste, garlic, lemon juice, and a hint of olive oil.",
        image: "/images/menu/tahina.png",
        price: 15,
    },
    {
        id: 6,
        name: "Seasoned Rice",
        description: "Fluffy seasoned rice, infused with aromatic herbs and spices, offering a fragrant and flavorful complement to any dish.",
        image: "/images/menu/seasoned-rice.png",
        price: 20,
    },
    {
        id: 7,
        name: "Mutton Kofta ( Seekh Kabab )",
        description: "Juicy mutton seekh kebabs, expertly seasoned with aromatic spices and grilled to perfection.",
        image: "/images/menu/kofta.png",
        price: 75,
    },
    {
        id: 8,
        name: "Potato Wedges",
        description: "Crispy potato wedges or golden French fries, seasoned to perfection and served with your choice of dipping sauce.",
        image: "/images/menu/potato-wedges.png",
        price: 25,
    },
    {
        id: 9,
        name: "Chicken Skewers",
        description: "Tender chicken skewers marinated in a flavorful blend of spices, grilled to juicy perfection, served with your choice of dipping sauce.",
        image: "/images/menu/chicken-skewers.png",
        price: 55,
    },
    {
        id: 10,
        name: "French Fries",
        description: "Golden French fries, perfectly crispy on the outside and fluffy on the inside, served with your favorite dipping sauce.",
        image: "/images/menu/french-fries.png",
        price: 20,
    },
];

export const grillParadiseItems = [
    {
        id: 11,
        name: "Caesar Salad",
        description: "Crisp romaine lettuce tossed with creamy Caesar dressing, Parmesan cheese, and homemade croutons.",
        image: "/images/menu/caesar-salad.png",
        price: 35,
    },
    {
        id: 12,
        name: "Grilled Chicken Bone",
        description: "Grilled chicken bone-in, seasoned to perfection and bursting with savory flavor, served with your choice of delectable sides.",
        image: "/images/menu/grilled-chicken.png",
        price: 65,
    },
    {
        id: 13,
        name: "Hummus",
        description: "Smooth and savory chickpea hummus, drizzled with extra virgin olive oil, and served with warm pita bread.",
        image: "/images/menu/hummus.png",
        price: 25,
    },
    {
        id: 14,
        name: "Pasta ( White or Pink )",
        description: "Al dente pasta served with your choice of creamy white sauce or tangy pink sauce, topped with freshly grated Parmesan cheese.",
        image: "/images/menu/pasta.png",
        price: 45,
    },
    {
        id: 15,
        name: "Tahina",
        description: "Rich and velvety tahini sauce made with sesame paste, garlic, lemon juice, and a hint of olive oil.",
        image: "/images/menu/tahina.png",
        price: 15,
    },
    {
        id: 16,
        name: "Seasoned Rice",
        description: "Fluffy seasoned rice, infused with aromatic herbs and spices, offering a fragrant and flavorful complement to any dish.",
        image: "/images/menu/seasoned-rice.png",
        price: 20,
    },
    {
        id: 17,
        name: "Mutton Kofta ( Seekh Kabab )",
        description: "Juicy mutton seekh kebabs, expertly seasoned with aromatic spices and grilled to perfection.",
        image: "/images/menu/kofta.png",
        price: 75,
    },
    {
        id: 18,
        name: "Potato Wedges or French Fries",
        description: "Crispy potato wedges or golden French fries, seasoned to perfection and served with your choice of dipping sauce.",
        image: "/images/menu/potato-wedges.png",
        price: 25,
    },
    {
        id: 19,
        name: "Chicken Skewers",
        description: "Tender chicken skewers marinated in a flavorful blend of spices, grilled to juicy perfection, served with your choice of dipping sauce.",
        image: "/images/menu/chicken-skewers.png",
        price: 55,
    },
    {
        id: 20,
        name: "Grilled Salmon and Seabass",
        description: "Grilled salmon and seabass fillets, delicately seasoned and cooked to perfection, served with a side of your choice for a delectable seafood experience.",
        image: "/images/menu/grilled-chicken.png",
        price: 95,
    },
];

export const extravaganzaItems = [
    {
        id: 21,
        name: "Caesar Salad",
        description: "Crisp romaine lettuce tossed with creamy Caesar dressing, Parmesan cheese, and homemade croutons.",
        image: "/images/menu/caesar-salad.png",
        price: 35,
    },
    {
        id: 22,
        name: "Grilled Chicken Bone",
        description: "Grilled chicken bone-in, seasoned to perfection and bursting with savory flavor, served with your choice of delectable sides.",
        image: "/images/menu/grilled-chicken.png",
        price: 65,
    },
    {
        id: 23,
        name: "Hummus",
        description: "Smooth and savory chickpea hummus, drizzled with extra virgin olive oil, and served with warm pita bread.",
        image: "/images/menu/hummus.png",
        price: 25,
    },
    {
        id: 24,
        name: "Pasta ( White or Pink )",
        description: "Al dente pasta served with your choice of creamy white sauce or tangy pink sauce, topped with freshly grated Parmesan cheese.",
        image: "/images/menu/pasta.png",
        price: 45,
    },
    {
        id: 25,
        name: "Tahina",
        description: "Rich and velvety tahini sauce made with sesame paste, garlic, lemon juice, and a hint of olive oil.",
        image: "/images/menu/tahina.png",
        price: 15,
    },
    {
        id: 26,
        name: "Seasoned Rice",
        description: "Fluffy seasoned rice, infused with aromatic herbs and spices, offering a fragrant and flavorful complement to any dish.",
        image: "/images/menu/seasoned-rice.png",
        price: 20,
    },
    {
        id: 27,
        name: "Mutton Kofta ( Seekh Kabab )",
        description: "Juicy mutton seekh kebabs, expertly seasoned with aromatic spices and grilled to perfection.",
        image: "/images/menu/kofta.png",
        price: 75,
    },
    {
        id: 28,
        name: "Potato Wedges or French Fries",
        description: "Crispy potato wedges or golden French fries, seasoned to perfection and served with your choice of dipping sauce.",
        image: "/images/menu/potato-wedges.png",
        price: 25,
    },
    {
        id: 29,
        name: "Chicken Skewers",
        description: "Tender chicken skewers marinated in a flavorful blend of spices, grilled to juicy perfection, served with your choice of dipping sauce.",
        image: "/images/menu/chicken-skewers.png",
        price: 55,
    },
    {
        id: 30,
        name: "Grilled Salmon and Seabass",
        description: "Grilled salmon and seabass fillets, delicately seasoned and cooked to perfection, served with a side of your choice for a delectable seafood experience.",
        image: "/images/menu/grilled-chicken.png",
        price: 95,
    },
    {
        id: 31,
        name: "Slightly Fried Calamari",
        description: "Tender calamari rings lightly fried to crispy perfection, served with zesty marinara sauce for a delightful appetizer or snack.",
        image: "/images/menu/french-fries.png",
        price: 65,
    },
    {
        id: 32,
        name: "Grilled Tiger Prawns",
        description: "Juicy grilled tiger prawns, seasoned to perfection and served with a side of your choice for a succulent seafood delight.",
        image: "/images/menu/chicken-skewers.png",
        price: 85,
    },
];

export const internationalItems = [
    {
        id: 33,
        name: "Caesar Salad",
        description: "Crisp romaine lettuce tossed with creamy Caesar dressing, Parmesan cheese, and homemade croutons.",
        image: "/images/menu/caesar-salad.png",
        price: 35,
    },
    {
        id: 34,
        name: "Grilled Chicken Bone",
        description: "Grilled chicken bone-in, seasoned to perfection and bursting with savory flavor, served with your choice of delectable sides.",
        image: "/images/menu/grilled-chicken.png",
        price: 65,
    },
    {
        id: 35,
        name: "Hummus",
        description: "Smooth and savory chickpea hummus, drizzled with extra virgin olive oil, and served with warm pita bread.",
        image: "/images/menu/hummus.png",
        price: 25,
    },
    {
        id: 36,
        name: "Pasta ( White or Pink )",
        description: "Al dente pasta served with your choice of creamy white sauce or tangy pink sauce, topped with freshly grated Parmesan cheese.",
        image: "/images/menu/pasta.png",
        price: 45,
    },
    {
        id: 37,
        name: "Tahina",
        description: "Rich and velvety tahini sauce made with sesame paste, garlic, lemon juice, and a hint of olive oil.",
        image: "/images/menu/tahina.png",
        price: 15,
    },
    {
        id: 38,
        name: "Seasoned Rice",
        description: "Fluffy seasoned rice, infused with aromatic herbs and spices, offering a fragrant and flavorful complement to any dish.",
        image: "/images/menu/seasoned-rice.png",
        price: 20,
    },
    {
        id: 39,
        name: "Potato Wedges or French Fries",
        description: "Crispy potato wedges or golden French fries, seasoned to perfection and served with your choice of dipping sauce.",
        image: "/images/menu/potato-wedges.png",
        price: 25,
    },
    {
        id: 40,
        name: "Chicken Skewers",
        description: "Tender chicken skewers marinated in a flavorful blend of spices, grilled to juicy perfection, served with your choice of dipping sauce.",
        image: "/images/menu/chicken-skewers.png",
        price: 55,
    },
    {
        id: 41,
        name: "Slightly Fried Calamari",
        price: 65,
        description: "Tender calamari rings lightly fried to crispy perfection, served with zesty marinara sauce for a delightful appetizer or snack.",
        image: "/images/menu/french-fries.png",
    },
    {
        id: 42,
        name: "Shrimp EGG Fried Rice",
        description: "Flavorful shrimp fried rice, cooked to perfection with fluffy grains, succulent shrimps, and a medley of fresh vegetables.",
        image: "/images/menu/seasoned-rice.png",
        price: 50,
    },
];

// All menu sections for the Catering Menu page
export const menuSections = [
    {
        id: MENU_CATEGORIES.GRILL_FEAST,
        title: "RICKYS GRILL FEAST",
        items: grillFeastItems,
    },
    {
        id: MENU_CATEGORIES.GRILL_PARADISE,
        title: "RICKYS GRILL PARADISE",
        items: grillParadiseItems,
    },
    {
        id: MENU_CATEGORIES.EXTRAVAGANZA,
        title: "RICKYS EXTRAVAGANZA",
        items: extravaganzaItems,
    },
    {
        id: MENU_CATEGORIES.INTERNATIONAL,
        title: "RICKYS INTERNATIONAL",
        items: internationalItems,
    },
];
